# Generated by Django 4.2.7 on 2025-08-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('position', models.CharField(choices=[('frontend', 'مطور واجهات أمامية'), ('backend', 'مطور خلفي'), ('fullstack', 'مطور شامل'), ('mobile', 'مطور تطبيقات جوال'), ('ui_ux', 'مصمم واجهات')], max_length=50, verbose_name='المنصب المرغوب')),
                ('experience_level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('expert', 'خبير')], max_length=20, verbose_name='مستوى الخبرة')),
                ('skills', models.TextField(verbose_name='المهارات التقنية')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='رابط معرض الأعمال')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='السيرة الذاتية')),
                ('cover_letter', models.TextField(verbose_name='خطاب تغطية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
            ],
            options={
                'verbose_name': 'طلب توظيف',
                'verbose_name_plural': 'طلبات التوظيف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=200, verbose_name='اسم الموقع')),
                ('domain', models.CharField(choices=[('real_estate', 'عقارات'), ('technology', 'تكنولوجيا'), ('education', 'تعليم'), ('healthcare', 'صحة'), ('business', 'أعمال'), ('ecommerce', 'تجارة إلكترونية'), ('portfolio', 'معرض أعمال'), ('blog', 'مدونة'), ('news', 'أخبار'), ('restaurant', 'مطعم'), ('other', 'أخرى')], max_length=50, verbose_name='مجال الموقع')),
                ('client_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='واتساب')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='تليجرام')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('additional_requirements', models.TextField(blank=True, null=True, verbose_name='متطلبات إضافية')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'طلب موقع',
                'verbose_name_plural': 'طلبات المواقع',
                'ordering': ['-created_at'],
            },
        ),
    ]
